services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    working_dir: /code/guvenlux
    build: .
    command: gunicorn guvenlux.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - ./guvenlux:/code/guvenlux
      - ./guvenlux/media:/code/guvenlux/media
      - ./guvenlux/staticfiles:/code/guvenlux/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env


    

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./guvenlux/static:/app/static:ro
      - ./guvenlux/media:/app/media:ro
      - ./nginx/certs:/etc/ssl/cloudflare:ro  
    depends_on:
      - web
    

volumes:
  postgres_data:
  certs:
