# Generated by Django 5.2.4 on 2026-01-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('index', 'Ana Sehife'), ('about', 'Haqqimizda'), ('contact', 'Bizimle Elaqe'), ('subcategory', 'Alt Kategorya Sehifesi'), ('products_detail', 'Mehsul Sehifesi'), ('products_list', 'Filterlenmis mehsullar shifesi')], default='index', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='background_images', verbose_name='Arxa plan şəkli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arxa plan şəkli',
                'verbose_name_plural': 'Arxa plan şəkilləri',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
            ],
            options={
                'verbose_name': 'Şirkət',
                'verbose_name_plural': 'Şirkətlər',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='guvenluxapp.category', verbose_name='Əsas kateqoriya')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='employees/')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='guvenluxapp.company')),
            ],
            options={
                'verbose_name': 'Terefdash',
                'verbose_name_plural': 'Terefdashlar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('description', models.TextField(max_length=500, verbose_name='Haqqında')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('price', models.FloatField(verbose_name='Qiymət')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Məhsul aktivliyi')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Ana səhifədə olacaq seçili məhsul')),
                ('main_category', models.ForeignKey(limit_choices_to={'parent_category__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_category_products', to='guvenluxapp.category', verbose_name='Əsas kateqoriya')),
                ('sub_category', models.ForeignKey(limit_choices_to={'parent_category__isnull': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_category_products', to='guvenluxapp.category', verbose_name='Alt kateqoriya')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Məhsul şəkli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guvenluxapp.product', verbose_name='Məhsul')),
            ],
            options={
                'verbose_name': 'Məhsul şəkli',
                'verbose_name_plural': 'Məhsul şəkilləri',
            },
        ),
    ]
