# Generated by Django 5.2.4 on 2026-02-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guvenluxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Tərəfdaş', 'verbose_name_plural': 'Tərəfdaşlar'},
        ),
    ]
