# Generated by Django 5.2.4 on 2025-07-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guvenluxapp', '0002_alter_category_options_category_slug_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='backgroundimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
