# Generated by Django 5.2.4 on 2025-07-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guvenluxapp', '0005_company_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
