# Generated by Django 5.2.4 on 2025-07-28 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guvenluxapp', '0006_employee_phone_employee_photo_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(limit_choices_to={'parent_category__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_category_products', to='guvenluxapp.category', verbose_name='Əsas kateqoriya'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(limit_choices_to={'parent_category__isnull': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_category_products', to='guvenluxapp.category', verbose_name='Alt kateqoriya'),
        ),
    ]
