# Generated by Django 5.2.4 on 2025-07-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guvenluxapp', '0007_remove_product_category_product_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='page',
            field=models.CharField(choices=[('index', 'Index Page'), ('about', 'About Page'), ('contact', 'Contact Page')], default='index', max_length=20),
        ),
    ]
