# Generated by Django 5.2.4 on 2025-07-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guvenluxapp', '0008_backgroundimage_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='page',
            field=models.CharField(choices=[('index', 'Ana Sehife'), ('about', 'Haqqimizda'), ('contact', 'Bizimle Elaqe')], default='index', max_length=20),
        ),
    ]
