# Generated by Django 5.2.4 on 2025-07-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guvenluxapp', '0009_alter_backgroundimage_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Shirket', 'verbose_name_plural': 'Shirketler'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Terefdash', 'verbose_name_plural': 'Terefdashlar'},
        ),
    ]
