# Generated by Django 5.2.4 on 2025-07-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guvenluxapp', '0010_alter_category_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='page',
            field=models.CharField(choices=[('index', 'Ana Sehife'), ('about', 'Haqqimizda'), ('contact', 'Bizimle Elaqe'), ('subcategory', 'Alt Kategorya Sehifesi')], default='index', max_length=20),
        ),
    ]
