# Generated by Django 5.2.4 on 2025-07-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guvenluxapp', '0011_alter_backgroundimage_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='page',
            field=models.CharField(choices=[('index', 'Ana Sehife'), ('about', 'Haqqimizda'), ('contact', 'Bizimle Elaqe'), ('subcategory', 'Alt Kategorya Sehifesi'), ('products_detail', 'Mehsul Sehifesi'), ('products_list', 'Filterlenmis mehsullar shifesi')], default='index', max_length=20),
        ),
    ]
