# Generated by Django 5.2.4 on 2025-07-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guvenluxapp', '0012_alter_backgroundimage_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='employees/default.jpg', upload_to='employees/'),
            preserve_default=False,
        ),
    ]
